apiVersion: v1
kind: Pod
metadata:
  name: nats-pub
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nats-pub
    image: natsio/nats-box
    command: ["nats", "pub", "-s", "nats://nats:4222", "test.subject", "Hello from NATS"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
  restartPolicy: Never
